Dimport java.text.simpleDateFormat;
import java.sql.*;
import project.ConnectionProvidER;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class issueBooks extends javax.swing.JPanel {

    /**
     * Creates new form issueBooks
     */
    public issueBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID-");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 126, 78, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID-");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 168, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Issue date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 215, 78, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Due date-");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 257, 78, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 126, 200, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 168, 200, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 311, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 51));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 215, 200, -1));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 0));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 255, 200, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue book.png"))); // NOI18N
        jButton3.setText("issue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 312, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String bookID=JTextField1.getText();
        String studentID=JTextField2.getText();
        String IssueDate=dFormat.Format(jDateChooser1.getDate());
        String DueDate=dFormat.Format(jDateChooser1.getDate());
        String returnBook="NO";
        try
        {
         connection con=ConnectionProvider.getCon();
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select * from book where bookID='"+bookID+"'");
         if(rs.next())
         {
             ResultSet rs1=st.executeQuery(select * from student where studentID='"+studentID+"'");
                    if(rsl.next())
                    {
                    }else
                        JOptionPane.showConfirmDialog(null."Incorrect studentID
         }
         else
             JOptionPane.ShowConfirmDialog(null,,"Incorrect bookID);
        }
        catch(exception e)
                {}
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
